### PR TITLE
Support target session connections

### PR DESCRIPTION
**Pull request by mafredri**
This PR improves the use case of communicating with targets via the Target domain (`SendMessageToTarget` / `ReceivedMessageFromTarget`).

~~This still has a few TODOs and is not production ready (e.g. calling `(*Client).Close()` multiple times will panic), but it should be ready for some testing.~~

I would love some feedback. I was working on a bigger improvement to Target management but decided to spin off the session part into it's own package.

Limitations:
* Commands issued over the emulated `rpcc.Conn` will always wait for confirmation from the original websocket that the command was delivered
    * E.g. running `go c.Page.Enable(nil); go c.Network.Enable(nil)` will work, but only one `Target.SendMessageToTarget` will be active at a time, and waiting for the response
    * This can be improved once `rpcc` supports async invocations (ref #18)

Example usage:

```go
// Initialize a new session client.
c := cdp.NewClient(conn) // cdp.Client with websocket connection.

sc, err := session.NewClient(c)
if err != nil {
	// Handle error.
}
defer sc.Close() // Cleanup.

// Establish a new session connection to targetID.
pageConn, err := sc.Dial(context.TODO(), targetID)
if err != nil {
	// Handle error.
}
defer pageConn.Close()

// Use the session connection.
pageClient := cdp.NewClient(pageConn)
err = pageClient.Page.Enable(context.TODO())
// ...
```

### CODE REVIEW

**Comment by djmally** [comment]
Haven't dug into the code just yet beyond reading some of the higher-level details, but let me give you a breakdown of what I've done so far:

- I swapped out some of my internal uses of `SendMessageToTarget` with the new `session` API, which was pretty simple and is _way_ less painful to use, so a good start right off the bat
- My workflow is as follows:
    - Create a new, isolated browser context with CreateBrowserContext, CreateTarget, & AttachToTarget
    - Create a `session.Client` from my existing `cdp.Client`, and then call `Dial` on that to attach to the browser context I just created
    - Create a new `cdp.Client` from the rpcc conn I got from dialing (I'm referring to this as `tabClient` internally)
I then use this client normally, to send commands to a target, which is working. The only problems come in cleaning up the `tabClient` and associated session connections.

To break down the cleanup process, here's what I tried, and what the result was:
```go
// Close the session rpcc connection
if err := sessionConn.Close(); err != nil {
    _ = logger.Error("Error closing session connection", "error", err)
    return err
}
// Close the session client
if err := auther.sessionClient.Close(); err != nil {
    _ = logger.Error("Error closing session client", "error", err)
    return err
}
// Dispose of the browser context we created earlier
_, err := client.Target.CloseTarget(context.Background(), target.NewCloseTargetArgs(targetID))
if err != nil {
    return err
}
disposeReply, err := cl.Target.DisposeBrowserContext(context.Background(), target.NewDisposeBrowserContextArgs(browserContextID))
if err != nil {
    return err
}
if !disposeReply.Success {
    return errors.New("Target.DisposeBrowserContext failed")
}
return nil
```
I haven't played around with reordering these statements yet, but I'm posting this in particular because I saw a bunch of messages coming out of `Client.watch`, which you said to look out for. Note that I edited some information out of these messages, private URLs and such.
```
Client.watch: orphan message: {"method":"Runtime.executionContextCreated","params":{"context":{"id":1,"origin":"://","name":"","auxData":{"isDefault":true,"frameId":"(42003BE8C0CD6BD47C34578A2C7DAE)"}}}}
Client.watch: orphan message: {"id":1,"result":{}}
Client.watch: orphan message: {"id":2,"result":{}}
Client.watch: orphan message: {"id":3,"result":{}}
Client.watch: orphan message: {"id":4,"result":{}}
Client.watch: orphan message: {"id":5,"result":{}}
Client.watch: orphan message: {"method":"Page.frameStartedLoading","params":{"frameId":"(42003BE8C0CD6BD47C34578A2C7DAE)"}}
Client.watch: orphan message: {"method":"Network.requestWillBeSent","params":{"requestId":"198.1","loaderId":"198.1","documentURL":"<url snipped>","request":{"url":"<url snipped>","method":"GET","headers":{"Upgrade-Insecure-Requests":"1","User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) HeadlessChrome/63.0.3239.132 Safari/537.36"},"mixedContentType":"none","initialPriority":"VeryHigh","referrerPolicy":"no-referrer-when-downgrade"},"timestamp":66720.73752,"wallTime":1516227986.37424,"initiator":{"type":"other"},"type":"Document","frameId":"(42003BE8C0CD6BD47C34578A2C7DAE)"}}
Client.watch: orphan message: {"method":"Network.responseReceived","params":{"requestId":"198.1","loaderId":"198.1","timestamp":66720.738921,"type":"Document","response":"<response snipped>}
Client.watch: orphan message: {"method":"Network.dataReceived","params":{"requestId":"198.1","timestamp":66720.739295,"dataLength":2375,"encodedDataLength":0}}
Client.watch: orphan message: {"method":"Runtime.executionContextDestroyed","params":{"executionContextId":1}}
Client.watch: orphan message: {"method":"Runtime.executionContextsCleared","params":{}}
Client.watch: orphan message: {"method":"Page.lifecycleEvent","params":{"frameId":"(42003BE8C0CD6BD47C34578A2C7DAE)","name":"commit","timestamp":66720.739722}}
Client.watch: orphan message: {"method":"Page.frameNavigated","params":{"frame":{"id":"(42003BE8C0CD6BD47C34578A2C7DAE)","loaderId":"198.1","url":"<response snipped>","mimeType":"text/html"}}}
Client.watch: orphan message: {"method":"Runtime.executionContextCreated","params":{"context":{"id":2,"origin":"<response snipped>","name":"","auxData":{"isDefault":true,"frameId":"(42003BE8C0CD6BD47C34578A2C7DAE)"}}}}
Client.watch: orphan message: {"method":"DOM.documentUpdated","params":{}}
Client.watch: orphan message: {"id":6,"result":{"frameId":"(42003BE8C0CD6BD47C34578A2C7DAE)"}}
```

Anyway,  things are looking very good so far. I will do some more testing on my end & then dig into the code further 😄

**Comment by mafredri** [comment]
Thanks for trying it out, I'm glad you find it useful! It's helpful to see how you ended up using it as well 😄.

> Create a session.Client from my existing cdp.Client, and then call Dial on that to attach to the browser context I just created

The `session.Client` isn't specific to the context, so feel free to keep it active for the lilfe-time of the main `cdp.Client` (websocket). The idea is that you create one, and use it to connect to Dial multiple targets.

Perhaps `session.Manager` would be a more descriptive name?

Another alternative would be to let each session do it's own management, in which case (essentially) the `session.Client.watch` method would be moved onto `session.session`. This would eradicate the need for a `session.Client` entirely (replaced by a single Dial method).

> EDIT: I think this was happening because I was closing both the session rpcc.Conn and the session client, which was causing a double-closure. Seems to be resolved by just closing the session client and not the connection or tab client.

The orphan messages don't really indicate any issue. It means that either a closed session is still receiving responses or that the messages are targeted to a session not created via `session.Client`.

Calling close on rpcc.Conn is ideal. However, at the moment the Detach command is run asynchronously in a goroutine. I think that should be changed so that Close waits for the session to close (on the Chrome side).

I'll try to take another look at this during the weekend. Feel free to report any other strange behaviors if you notice them! 🙂!

**Comment by matthewmueller** [comment]
So happy to see this coming along. Thanks for all your hard work @mafredri. I'll be trying this today and will let you know if I run into anything :-)

**Comment by matthewmueller** [comment]
> The orphan messages don't really indicate any issue. It means that either a closed session is still receiving responses or that the messages are targeted to a session not created via session.Client.

Similar feedback – really nice work! Works a lot better than what I was originally doing :-)

Would like to disable the logging of the orphaned messages since most of the events I don't care about, though I can see a use case for wanting to see everything too. Right now you're only showing events when subscribed on initial websocket connection, I think it should probably act similarly for target connections.

I can definitely see a use case for wanting to see all events during debugging, but I haven't needed it yet. Perhaps there could be a debug logger interface that gets passed in?

**Comment by mafredri** [comment]
Thanks for the feedback @matthewmueller, glad you like it.

> Would like to disable the logging of the orphaned messages since most of the events I don't care about, though I can see a use case for wanting to see everything too.

Absolutely, I never intended to leave the logging in. I was just interested to see if it would give us any hints of potential problems.

> Right now you're only showing events when subscribed on initial websocket connection, I think it should probably act similarly for target connections.

Sorry, I don't quite understand what you mean. In my mind the behavior should be the same. Could you clarify?

> I can definitely see a use case for wanting to see all events during debugging, but I haven't needed it yet. Perhaps there could be a debug logger interface that gets passed in?

I think it makes sense to log on the underlying (websocket) connection since all session traffic can be inspected there as well. So I don't think `session` necessarily has a need for logging, but I'll take this under consideration.

**Comment by matthewmueller** [comment]
> Sorry, I don't quite understand what you mean. In my mind the behavior should be the same. Could you clarify?

No that's my bad, I didn't explain it very well. All I meant was that in case you wanted to keep the logging, it may make sense to log orphan messages on the "initial websocket" too. 

Looks like this is a moot point though since you removed it – thanks!

**Comment by djmally** [comment]
@mafredri apologies for this falling off my radar-- I was dealing with a family emergency for a few weeks. Any word on when this might get merged? I'm looking forward to using it 😃

**Comment by mafredri** [comment]
@djmally no worries, happens to all of us. I'll try to get this sorted tomorrow, or early next week. Sorry for the hold-up 😄!

**Comment by mafredri** [comment]
@djmally @matthewmueller this is essentially ready for merge now and I'll be merging it in the coming days. If you have any input I'd love to hear it. I won't ask you to review the code, but this is what the package doc looks like (generated by godoc):

```
PACKAGE DOCUMENTATION

package session
    import "github.com/mafredri/cdp/session"

    Package session implements a session Client for establishing session
    connections to targets (via the Target domain). Session connections
    allow a single websocket connection (from the provided cdp.Client) to be
    used for communicating with multiple targets.

    Initialize a new session client.

	c := cdp.NewClient(conn) // cdp.Client with websocket connection.

	sc, err := session.NewClient(c)
	if err != nil {
		// Handle error.
	}
	defer sc.Close() // Cleanup.

    Establish a new session connection to targetID.

	pageConn, err := sc.Dial(context.TODO(), targetID)
	if err != nil {
		// Handle error.
	}
	defer pageConn.Close()

    Use the session connection.

	pageClient := cdp.NewClient(pageConn)
	err = pageClient.Page.Enable(context.TODO())
	// ...

    If session connections are behaving unexpectedly, you can debug the
    session Manager by checking the error channel.

	go func() {
		for {
			err, ok := <-m.Err()
			if !ok { // Manager is closed.
				return
			}
			log.Println(err)
		}
	}()

TYPES

type Manager struct {
    // contains filtered or unexported fields
}
    Manager establishes session connections to targets.

func NewManager(c *cdp.Client) (*Manager, error)
    NewManager creates a new session Manager.

    The cdp.Client will be used to listen to events and invoke commands on
    the Target domain. It will also be used by all rpcc.Conn created by
    Dial.

func (m *Manager) Close() error
    Close closes the Manager and all active sessions. All rpcc.Conn created
    by Dial will be closed.

func (m *Manager) Dial(ctx context.Context, id target.ID) (*rpcc.Conn, error)
    Dial establishes a target session and creates a lightweight rpcc.Conn
    that uses SendMessageToTarget and ReceivedMessageFromTarget from the
    Target domain instead of a new websocket connection.

    Dial will invoke AttachToTarget. Close (rpcc.Conn) will invoke
    DetachFromTarget.

func (m *Manager) Err() <-chan error
    Err is a channel that blocks until the Manager encounters an error. The
    channel is closed if Manager is closed.

    Errors could happen if the debug target sends events that cannot be
    decoded from JSON.

```

**Comment by djmally** [comment]
@mafredri I think there may be some out-of-date information in the Godoc; there's a reference to `session.NewClient`, but isn't that `session.NewManager` now? Otherwise looks great!

**Comment by matthewmueller** [comment]
Awesome! Thanks for all your hard work on this – I've been using this branch for awhile now with no problems :-)

**Comment by mafredri** [comment]
Good catch @djmally! I did update the earlier documentation but I must've forgotten to commit it 🤦‍♂️.

Fantastic @matthewmueller, glad to hear it!

Thanks for your input, both of you!

**Pull request merged**
